### ISSUE TITLE
Unable to send log via yii\debug\LogTarget: Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: yii\console\Request::getAbsoluteUrl()

### ISSUE THREAD

**Issue by final3987** [yiisoft/yii2-app-advanced#439] opened 2019-08-14 13:05 UTC
Unable to send log via yii\debug\LogTarget: Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: yii\console\Request::getAbsoluteUrl()

    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "2.0.14",
        "yiisoft/yii2-bootstrap": "2.0.0",
        "yiisoft/yii2-swiftmailer": "2.0.0 || 2.1.0",
        "yiisoft/yii2-queue": "2.3.0",
        "yiisoft/yii2-httpclient": "*",
        "yiisoft/yii2-redis": "2.0@dev",
        "google/auth": "dev-master",
        "leafo/lessphp": "0.4.*",
        "linslin/yii2-curl": "*",
        "guzzlehttp/guzzle": ">=4.1.4 <7.0"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "2.1.0",
        "yiisoft/yii2-gii": "2.1.0",
        "yiisoft/yii2-faker": "2.0.0",
        "codeception/base": "^2.4.0",
        "phpunit/phpunit": "~6.5.5",
        "codeception/verify": "~1.1.0",
        "symfony/browser-kit": ">=2.7 <=4.2.4"
    },

**Comment by samdark** [comment] 2019-08-15 09:09
Duplicate of https://github.com/yiisoft/yii2-debug/issues/406

**Closed by samdark** 2019-08-15 09:09 UTC
