### ISSUE TITLE
Some checks were not successful when pushing changes on a Yii advanced template

### ISSUE THREAD

**Issue by abdelilahdahdahi** [yiisoft/yii2-app-advanced#560] opened 2023-10-21 09:54 UTC
### What steps will reproduce the problem?
Pushing to the Github repository "https://github.com/abdelilahdahdahi/Engineers-Lens", you can find the issues there
### What's expected?
Successful builds for PHP versions 7.4 - 8.0 and 8.1
### What do you get instead?
Some checks were not successful: 2 failing and 1 cancelled checks

### Additional info
**First check: PHP 7.4-mysql-5.7**
Install dependencies with composer
Loading composer repositories with package information
Error: curl error 28 while downloading https://repo.packagist.org/packages.json: Failed to connect to repo.packagist.org port 443 after 5220 ms: Connection timed out

In CurlDownloader.php line 372:
curl error 28 while downloading 
https://repo.packagist.org/packages.json: F  
  ailed to connect to repo.packagist.org port 443 after 5220 ms: Connection t  
  imed out                                                                     

`update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>...]`

Error: Process completed with exit code 1

-----------------------------------------------------------------------
**Second check: PHP 8.0-mysql-5.7**
Generating optimized autoload files
Class frontend\tests\FunctionalTester located in ./frontend/tests/_support/FunctionalTester.php does not comply with psr-4 autoloading standard. Skipping.
Class frontend\tests\UnitTester located in ./frontend/tests/_support/UnitTester.php does not comply with psr-4 autoloading standard. Skipping.
Class common\tests\UnitTester located in ./common/tests/_support/UnitTester.php does not comply with psr-4 autoloading standard. Skipping.
Class backend\tests\FunctionalTester located in ./backend/tests/_support/FunctionalTester.php does not comply with psr-4 autoloading standard. Skipping.
Class backend\tests\UnitTester located in ./backend/tests/_support/UnitTester.php does not comply with psr-4 autoloading standard. Skipping.
56 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Error: The operation was canceled.

-------------------------------------------------------------------------
**Third check: PHP 8.1-mysql-5.7**
Cache dependencies installed with composer
Cache not found for input keys: php8.1-composer--d51ccd1b7aed9df0ebe310fc45b2e1151c3981f19539d086d86caaf5dc951992, php8.1-composer--.
Error: The operation was canceled.

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.49 (I'm not sure)
| PHP version      | 7.4 - 8.0 - 8.1
| Operating system | Windows

**Comment by bizley** [comment] 2023-10-21 16:20
I'm not sure what exactly is the issue here. I see problem on your side with the packagist so far. Please provide us with the minimum data to reproduce the problem while clearly stating what it is.

**Comment by abdelilahdahdahi** [comment] 2023-10-22 07:39
Hi, thanks for replying!
Yes, as you said I think the problem is with the packagist, I have no clue why it's failing in Github.
I just created a brand new Yii advanced template and pushed it to Github, it keeps saying "Some checks were not successful: builds for PHP versions 7.4 - 8.0 and 8.1"

**Comment by abdelilahdahdahi** [comment] 2023-10-22 07:47
Here are some details:
<img width="335" alt="image" src="https://github.com/yiisoft/yii2-app-advanced/assets/76753930/781a63aa-7252-4a41-9bc4-c09a9c6c3165">
<img width="511" alt="image" src="https://github.com/yiisoft/yii2-app-advanced/assets/76753930/81f243ea-6bd0-441c-b663-9e80f6fcfc53">

**Comment by terabytesoftw** [comment] 2023-10-22 09:33
`git update-index --chmod=+x init`

**Comment by abdelilahdahdahi** [comment] 2023-10-22 09:47
Would you like to give some info or context for this command please? Why should I use it and what it actually does?

**Comment by thelizardreborn** [comment] 2024-04-30 02:37
@abdelilahdahdahi It adjusts the permission bits of the init script to allow it to be executable. It's the solution to the error you are getting: `./init: Permission denied`

**Comment by samdark** [comment] 2024-05-06 11:45
Closing since it's not Yii issue.

**Closed by samdark** 2024-05-06 11:45 UTC
Labels: status:need more info
