### ISSUE TITLE
Violation of UNIQUE KEY constraint for column password_reset_token

### ISSUE THREAD

**Issue by varan82** [yiisoft/yii2-app-advanced#88] opened 2015-11-10 18:39 UTC
Integrity constraint violation – yii\db\IntegrityException

SQLSTATE[23000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Violation of UNIQUE KEY constraint 'UQ__user__665877D008EA5793'. Cannot insert duplicate key in object 'dbo.user'.

Error Info: Array
(
    [0] => 23000
    [1] => 2627
    [2] => [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Violation of UNIQUE KEY constraint 'UQ__user__665877D008EA5793'. Cannot insert duplicate key in object 'dbo.user'.
)

**Comment by varan82** [comment] 2015-11-10 18:41
when i try to signup a user 
DB is on MS SQL SERVER 2008 R2

**Comment by varan82** [comment] 2015-11-10 19:15
to fix the issue i should change the key type from Unique to Index(is unique= true)
and add a filter to the index UQ__user__665877D008EA5793 (password_reset_token is not null)

**Comment by samdark** [comment] 2016-07-25 23:10
Closing since unable to reproduce and long time passed...

**Closed by samdark** 2016-07-25 23:10 UTC
